export const routeNames = {
  fundList: 'fund-list',
  fundDetail: 'fund-detail',
  fundReportDetail: 'fund-report-detail',
  fundNavQuality: 'fund-nav-quality',
  estimateDriftList: 'estimate-drift-list',
  estimateDriftDetail: 'estimate-drift-detail',
  fundEstimateLogs: 'fund-estimate-logs',
  manualIndexMappings: 'manual-index-mappings',
  indexQuoteSources: 'index-quote-sources',
  operations: 'operations',
  fundNavHistory: 'fund-nav-history',
  fundNavHistoryTask: 'fund-nav-history-task',
  aStockHistory: 'a-stock-history',
  aStockHistoryTask: 'a-stock-history-task',
} as const
