services:
  backend:
    build:
      context: ./backend
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.mirrors.ustc.edu.cn/simple/}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-pypi.mirrors.ustc.edu.cn}
    image: fund-nav-estimator-backend:${DEPLOY_ENV:-prod}
    restart: unless-stopped
    newwork_mode: bridge
    env_file:
      - ./backend/.env
    environment:
      APP_ENV: ${DEPLOY_ENV:-local}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - /share/Container/fund-nav-estimator/test/backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
      target: build
      args:
        VITE_APP_BASE_PATH: ${VITE_APP_BASE_PATH:-/fund-nav-estimator/}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-}
    image: fund-nav-estimator-frontend:${DEPLOY_ENV:-prod}
    command: sh -c "rm -rf /dist/* && cp -a /app/dist/. /dist/"
    volumes:
      - /share/Container/fund-nav-estimator/test/frontend/dist:/dist
    profiles:
      - build
