FROM 192.168.50.50:16060/markz/python-runtime:py3.14-slim

WORKDIR /app

ARG PIP_INDEX_URL=http://192.168.50.50:16666/repository/pypi-group/simple/
ARG PIP_TRUSTED_HOST=192.168.50.50

COPY requirements.txt .
RUN python -m pip install --no-cache-dir --upgrade pip \
        -i "${PIP_INDEX_URL}" \
        --trusted-host "${PIP_TRUSTED_HOST}" \
        --timeout 120 \
    && python -m pip install --no-cache-dir -r requirements.txt \
        -i "${PIP_INDEX_URL}" \
        --trusted-host "${PIP_TRUSTED_HOST}" \
        --timeout 120
